name: 백엔드 도커 이미지 빌드 및 배포

on:
  push:
    branches: ["main", "master"]  # 배포할 브랜치를 여기서 지정
  pull_request:
    branches: ["main", "master"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1) GitHub Actions에서 소스 코드 체크아웃
      - name: 소스 코드 체크아웃
        uses: actions/checkout@v3

      # 2) Docker Hub 로그인 (Secrets 필요)
      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3) buildx 설정
      - name: Docker 빌드x 설정
        uses: docker/setup-buildx-action@v2

      # 4) 이미지 태그 메타데이터 생성
      - name: 이미지 태그 생성
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/tetris-backend
          tags: |
            type=raw,value=latest
            type=sha,format=short

      # 5) 빌드 & 푸시
      - name: 도커 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          context: ./tetris/backend        # 백엔드 소스 경로 (현재 예시)
          file: ./tetris/backend/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}  # PR 시에는 push 하지 않음
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # 여러 플랫폼을 지원하려면 아래처럼 작성 (M1 등 고려 시)
          platforms: linux/amd64,linux/arm64