name: 테트리스 도커 이미지 빌드 및 배포

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
      # 코드 체크아웃
      - name: 저장소 체크아웃
        uses: actions/checkout@v3
      
      # Docker Hub 로그인
      - name: Docker Hub 로그인
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      
      # Docker 빌드 및 푸시 설정
      - name: Docker 빌드 및 푸시 설정
        uses: docker/setup-buildx-action@v2
      
      # 이미지 태그 생성 (버전 관리용)
      - name: 이미지 태그 생성
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKERHUB_USERNAME }}/tetris
          tags: |
            type=raw,value=latest
            type=sha,format=short
      
      # Docker 이미지 빌드 및 푸시
      - name: 이미지 빌드 및 푸시
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./tetris/Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max 